name: CI/CD Pipeline

on:
  push:
    branches:
      - main     

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3 

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.MYDOCKERHUB }}
        password: ${{ secrets.DOCKER_HUB_PASS }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{secrets.USERNAME1}}/wisecow_img:myapp1 .
        docker push ${{secrets.USERNAME1}}/wisecow_img:myapp1

  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" 
        sudo apt install unzip
        sudo unzip awscliv2.zip  
        sudo ./aws/install
        aws --version

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Install aws-iam-authenticator
      run: |
        curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/linux/amd64/aws-iam-authenticator
        chmod +x aws-iam-authenticator
        sudo mv aws-iam-authenticator /usr/local/bin/

    - name: Update kubeconfig
      run: aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.AWS_EKS_CLUSTER_NAME }}
    
    - name: Print kubeconfig
      run: cat $HOME/.kube/config


    - name: Deploy to EKS
      env:
        KUBECONFIG: /home/runner/.kube/config
      run: |
        kubectl apply -f wisecow-deployment.yaml --validate=false
        kubectl apply -f wisecow-service.yaml --validate=false

    - name: Check Kubernetes Deployment
      run: kubectl rollout status deployment/myapp-deployment
