name: CI/CD Pipeline

on:
  push:
    branches:
      - main     

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3 

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.MYDOCKERHUB }}
        password: ${{ secrets.DOCKER_HUB_PASS }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{secrets.USERNAME1}}/wisecow_img:myapp1 .
        docker push ${{secrets.USERNAME1}}/wisecow_img:myapp1

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Check kubeconfig
      run: cat ~/.kube/config

    - name: Debug SSH Connection
      run: ssh -v -o StrictHostKeyChecking=no ubuntu@13.201.100.123 "ls -la ~/.kube/config"

    
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f wisecow-deployment.yaml --validate=false
        kubectl apply -f wisecow-service.yaml --validate=false
   
